version: '3.8'

services:

  # PHP Apache
  php-apache:
    build: ./php
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    restart: always
    depends_on:
      - mysql-container

  # MySQL
  mysql-container:
    build: ./sql
    ports:
      - 3306:3306
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: sample_root_password
      # MYSQL_DATABASE: sample_db
      # MYSQL_USER: sample_user
      - MYSQL_ROOT_PASSWORD=pass

  # phpmyadminコンテナ
  pma-container:
    # イメージはphpmyadminを選択します
    image: phpmyadmin/phpmyadmin
    # 環境変数の設定
    environment:
      - PMA_HOST=mysql-container
      - PMA_USER=root
      - PMA_PASSWORD=pass
    # 外部ブラウザからのアクセスポート:内部コンテナのポートの接続
    # - 8080:80
    ports:
      - 8082:80
    # 起動順序 mysql-containerの後
    depends_on:
      - mysql-container
    restart: always
    volumes:
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
      - ./sql/data:/var/lib/mysql